// Refactoring Web Component/angularcomponent/src/app/footerpage.component.ts
import { Component, Input, AfterViewInit, OnInit } from '@angular/core';

@Component({
  selector: 'footer-page',
  template:`
  <h1>W3CSS footer component example</h1>
  <pre><code>&lt;ng-footer 
  [contact]="[{{'{'}}name:'fb', link:'https://www.facebook.com', icon:'fa fa-facebook-official'{{'}'}},
              {{'{'}}name: 'twitter', link:'https://twitter.com', icon: 'fa fa-twitter'{{'}'}}]"&gt;
&lt;/ng-footer&gt;</code></pre>
    <ng-footer [contact]="[{name:'fb', link:'https://www.facebook.com', icon:'fa fa-facebook-official'},
                           {name: 'twitter', link:'https://twitter.com', icon: 'fa fa-twitter'}]"
               >
    </ng-footer>

  `
})
export class FooterPageComponent{

}

// Refactoring Web Component/vuecomponent/src/components/footerpage.vue
<template lang="html">
  <div>
    <h1>W3CSS footer component example</h1>
<pre><code>&lt;footer-component 
  :contact="[{name:'fb', link:'https://www.facebook.com', icon:'fa fa-facebook-official'},
             {name: 'twitter', link:'https://twitter.com', icon: 'fa fa-twitter'}]"
  powerby="taiyi"&gt;
&lt;/footer-component&gt;
</code></pre>
    <footer-component :contact="[{name:'fb', link:'https://www.facebook.com', icon:'fa fa-facebook-official'},
                           {name: 'twitter', link:'https://twitter.com', icon: 'fa fa-twitter'}]"
                      powerby="taiyi">
    </footer-component>
  </div>
</template>

<script lang="js">
  import FooterComponent from './FooterComponent'
  export default  {
    name: 'footerpage',
    props: [],
    components: {FooterComponent}
}
</script>

<style scoped lang="css">
</style>
