// Refactoring Web Component/angularcomponent/src/app/imgSlide.component.ts
import { Component, Input, AfterViewInit, OnInit } from '@angular/core';

@Component({
  selector: 'ng-imgslide',
  template:`
  <div class="slideshow-container">
    <div class="mySlides" *ngFor="let img of imgs; let i = index">
      <div class="numbertext">{{i+1}}/{{imgLength}}</div>
      <img src={{img}} style="width:100%">
      <div class="text" *ngIf="captions">{{captions[i]}}</div>
    </div>

    <!-- Next and previous buttons -->
    <a class="prev" (click)="plusSlides(-1)">&#10094;</a>
    <a class="next" (click)="plusSlides(1)">&#10095;</a>
  </div>
  <br>  

  <div style="text-align:center">
    <span class="dot" *ngFor="let img of imgs; let i = index" (click)="currentSlide(i+1)"></span>
  </div>
  `,
  styleUrls:['./imgSlide.component.css']
})
export class NGImgSlideComponent implements AfterViewInit,OnInit{
  @Input() imgs;
  @Input() captions;
  slideIndex = 1;
  imgLength;

  ngOnInit(){
    this.imgLength = this.imgs.length;
  }
  ngAfterViewInit(){
    this.showSlides(this.slideIndex);
  }

  plusSlides(n) {
    this.showSlides(this.slideIndex += n);
  }
  
  currentSlide(n) {
    this.showSlides(this.slideIndex = n);
  }
  
  showSlides(n) {
    var i;
    var slides = document.querySelectorAll(".mySlides") as NodeListOf<HTMLElement>;
    var dots = document.querySelectorAll(".dot") as NodeListOf<HTMLElement>;

    if (n > slides.length) {this.slideIndex = 1} 
    if (n < 1) {this.slideIndex = slides.length}
    for (i = 0; i < slides.length; i++) {
        slides[i].style.display = "none"; 
    }
    for (i = 0; i < dots.length; i++) {
        dots[i].className = dots[i].className.replace(" active", "");
    }
    slides[this.slideIndex-1].style.display = "block"; 
    dots[this.slideIndex-1].className += " active";
  }
}

// Refactoring Web Component/vuecomponent/src/components/ImgSlide.vue
<template lang="html">
<div>
  <div class="slideshow-container">
    <div class="mySlides fade" v-for="(img, index) in imgs">
      <div class="numbertext">{{index+1}} / 3</div>
      <img :src="img" style="width:100%">
      <div class="text">{{captions[index]}}</div>
    </div>
    
    <a class="prev" v-on:click="plusSlides(-1)">&#10094;</a>
    <a class="next" v-on:click="plusSlides(1)">&#10095;</a>

  </div>
  <br>

  <div style="text-align:center">
    <span class="dot" v-on:click="currentSlide(1)"></span> 
    <span class="dot" v-on:click="currentSlide(2)"></span> 
    <span class="dot" v-on:click="currentSlide(3)"></span> 
  </div>
</div>
</template>

<script lang="js">
  export default  {
    name: 'img-slide',
    props: ['imgs','captions'],
    mounted() {
      this.showSlides(this.slideIndex);
    },
    data() {
      return{
        slideIndex: 1
      }
    },
    methods: {
      plusSlides: function(n) {
        this.showSlides(this.slideIndex += n);
      },
      currentSlide: function(n) {
        this.showSlides(this.slideIndex = n);
      },
      showSlides: function (n) {
        var i;
        var slides = document.getElementsByClassName("mySlides");
        var dots = document.getElementsByClassName("dot");
        if (n > slides.length) {this.slideIndex = 1}    
        if (n < 1) {this.slideIndex = slides.length}
        for (i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";  
        }
        for (i = 0; i < dots.length; i++) {
            dots[i].className = dots[i].className.replace(" active", "");
        }
        slides[this.slideIndex-1].style.display = "block";  
        dots[this.slideIndex-1].className += " active";
      }
    },
    computed: {

    }
}
</script>

<style scoped lang="css">
* {box-sizing: border-box}
body {font-family: Verdana, sans-serif; margin:0}
.mySlides {display: none}
img {vertical-align: middle;}

/* Slideshow container */
.slideshow-container {
  max-width: 1000px;
  position: relative;
  margin: auto;
}

/* Next & previous buttons */
.prev, .next {
  cursor: pointer;
  position: absolute;
  top: 50%;
  width: auto;
  padding: 16px;
  margin-top: -22px;
  color: white;
  font-weight: bold;
  font-size: 18px;
  transition: 0.6s ease;
  border-radius: 0 3px 3px 0;
  user-select: none;
}

/* Position the "next button" to the right */
.next {
  right: 0;
  border-radius: 3px 0 0 3px;
}

/* On hover, add a black background color with a little bit see-through */
.prev:hover, .next:hover {
  background-color: rgba(0,0,0,0.8);
}

/* Caption text */
.text {
  color: #f2f2f2;
  font-size: 15px;
  padding: 8px 12px;
  position: absolute;
  bottom: 8px;
  width: 100%;
  text-align: center;
}

/* Number text (1/3 etc) */
.numbertext {
  color: #f2f2f2;
  font-size: 12px;
  padding: 8px 12px;
  position: absolute;
  top: 0;
}

/* The dots/bullets/indicators */
.dot {
  cursor: pointer;
  height: 15px;
  width: 15px;
  margin: 0 2px;
  background-color: #bbb;
  border-radius: 50%;
  display: inline-block;
  transition: background-color 0.6s ease;
}

.active, .dot:hover {
  background-color: #717171;
}

/* Fading animation */
.fade {
  -webkit-animation-name: fade;
  -webkit-animation-duration: 1.5s;
  animation-name: fade;
  animation-duration: 1.5s;
}

@-webkit-keyframes fade {
  from {opacity: .4} 
  to {opacity: 1}
}

@keyframes fade {
  from {opacity: .4} 
  to {opacity: 1}
}

/* On smaller screens, decrease text size */
@media only screen and (max-width: 300px) {
  .prev, .next,.text {font-size: 11px}
}
</style>
