// Refactoring Web Component/angularcomponent/src/app/jsavpage/jsavpage.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-jsavpage',
  templateUrl: './jsavpage.component.html',
  styleUrls: ['./jsavpage.component.css']
})
export class JsavpageComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<h1>JSAV array</h1>
<pre><code>&lt;app-jsavarr [datas]=[9,12,14,23,25,31,34,35]&gt;&lt;/app-jsavarr&gt;</code></pre>
<app-jsavarr [datas]=[9,12,14,23,25,31,34,35]></app-jsavarr>
<h1>JSAV binary search</h1>
<pre><code>&lt;app-jsav-binary-search [sizes]=20&gt;&lt;/app-jsav-binary-search&gt;</code></pre>
<app-jsav-binary-search [sizes]=20></app-jsav-binary-search>

// Refactoring Web Component/vuecomponent/src/components/jsavpage.vue
<template lang="html">
  <div>
    <h1>JSAV array</h1>
    <pre><code>&lt;jsavarr-component :datas="[2,5,15,43,12,36,13]"&gt;&lt;/jsavarr-component&gt;</code></pre>
    <jsavarr-component :datas="[2,5,15,43,12,36,13]"></jsavarr-component>
    <h1>JSAV binary search</h1>
    <pre><code>&lt;jsav-binary-component :sizes=15&gt;&lt;/jsav-binary-component&gt;</code></pre>
    <jsav-binary-component :sizes=15></jsav-binary-component>
  </div>
</template>

<script lang="js">
  import JsavarrComponent from './JsavarrComponent';
  import JsavBinaryComponent from './JsavBinaryComponent';
  export default  {
    name: 'jsavpage',
    props: [],
    components: {JsavarrComponent, JsavBinaryComponent},
    mounted() {

    },
    data() {
      return {

      }
    },
    methods: {

    },
    computed: {

    }
}
</script>

<style scoped lang="css">
  .jsavpage {

  }
</style>
