// Refactoring Web Component/angularcomponent/src/app/jsavpage/jsavarr/jsavarr.component.ts
import { Component, OnInit, Input, AfterViewInit } from '@angular/core';

declare var JSAV: any;

@Component({
  selector: 'app-jsavarr',
  templateUrl: './jsavarr.component.html',
  styleUrls: ['./jsavarr.component.css']
})
export class JsavarrComponent implements OnInit,AfterViewInit {
  @Input() datas;
  constructor() { }

  ngOnInit() {
  }
  ngAfterViewInit(){
      var av = new JSAV("container-jsavarr");
      var theArray = this.datas;
      var arr = av.ds.array(theArray, {indexed: false});
      av.displayInit();
    }
}

<div id="container-jsavarr"></div>

// Refactoring Web Component/vuecomponent/src/components/JsavarrComponent.vue
<template lang="html">
  <div>
    <div id="container-jsavarr"></div>
  </div>
</template>

<script lang="js">
  export default  {
    name: 'jsavarr-component',
    props: ['datas'],
    mounted() {
      var av = new JSAV("container-jsavarr");
      var arr = av.ds.array(this.datas, {indexed: false});
      av.displayInit();
    },
    data() {
      return {
      }
    }
}
</script>

<style scoped lang="css">
</style>
