// Refactoring Web Component/vuecomponent/src/components/imgpage.vue
<template lang="html">

  <section class="imgpage">
    <h1>Img Slide component</h1>
    <pre><code>&lt;img-slide  :imgs="['https://www.w3schools.com/howto/img_mountains_wide.jpg',
                    'https://www.w3schools.com/howto/img_lights_wide.jpg',
                    'https://www.w3schools.com/howto/img_snow_wide.jpg']"
            :captions="['Mountains', 'Light', 'Snow']"&gt;
&lt;/img-slide&gt;
</code></pre>
    <img-slide :imgs="['https://www.w3schools.com/howto/img_mountains_wide.jpg',
                          'https://www.w3schools.com/howto/img_lights_wide.jpg',
                          'https://www.w3schools.com/howto/img_snow_wide.jpg']"
               :captions="['Mountains', 'Light', 'Snow']"
    ></img-slide>
  </section>

</template>

<script lang="js">
  import ImgSlide from './ImgSlide';
  export default  {
    name: 'imgpage',
    props: [],
    components: {ImgSlide},
    mounted() {

    },
    data() {
      return {

      }
    },
    methods: {

    },
    computed: {

    }
}
</script>

<style scoped lang="css">
  .imgpage {

  }
</style>

// Refactoring Web Component/angularcomponent/src/app/imgpage.component.ts
import { Component, Input, AfterViewInit, OnInit } from '@angular/core';

@Component({
  selector: 'img-page',
  template:`
    <h1>Img Slide component</h1>
    <pre><code>&lt;ng-imgslide 
    [imgs]="['https://www.w3schools.com/howto/img_band_chicago.jpg',
             'https://www.w3schools.com/howto/img_band_ny.jpg',
             'https://www.w3schools.com/howto/img_band_la.jpg']"
    [captions]="['Mountains', 'Light', 'Snow']"&gt;
&lt;/ng-imgslide&gt;</code></pre>

    <ng-imgslide [imgs]="['https://www.w3schools.com/howto/img_mountains_wide.jpg',
                          'https://www.w3schools.com/howto/img_lights_wide.jpg']"
                 [captions]="['Mountains', 'Light']">
    </ng-imgslide>
  `
})
export class ImgPageComponent{

}
